### PR TITLE
Fix/translate to pt br

### PR DESCRIPTION
**Pull request by pethersonmoreno**
- removed flashing screen to translate the page
 - When load the page without pre load the resources `resources: loadLanguageResources(languages, languageNamespaces),`, the page shines before translate
- removed not used copy locales
- removed /{lang}/ path because not work with subpath
  - i18nPlugin doesn't work with subpath like /subfolder/en/, only /en/
  - then if it uses pathPrefix the translation doesn't work as desired

### CODE REVIEW

**Comment by pethersonmoreno** [comment]
@halkeye , could you validate these changes, I was doing it when you merged the other Pull request.

**Comment by halkeye** [comment]
I saw some formatting issues. Can you merge  #25 when it merges. and then run `yarn lint --fix` when its done?

**Comment by pethersonmoreno** [comment]
Applied the merge https://github.com/halkeye/gatsby-theme-nodeschool/pull/25 using your current master and already ran `yarn lint --fix`.
@halkeye, could you validate it again?

**Comment by pethersonmoreno** [comment]
Applied the merge https://github.com/halkeye/gatsby-theme-nodeschool/pull/25 using your Current master and already ran `yarn lint --fix`.
@halkeye, could you validate it again?

**Comment by halkeye** [comment]
Sorry I've just been busy, I'll try to get to it this weekend

**Comment by halkeye** [comment]
I certainly need to spend a bunch of time reviewing what gatsby-theme-localization does, but this change  doesn't break any of the yvr sutff, and if it works for you, then I'm happy with the change.

**Pull request merged**
